
/* menu */
	EB_MULTI_LANG_BEGIN(NULL, NULL) {
		EB_LANG_ADD("lansetting", 			"Lan口设置", 	"Lan Setting"),
		EB_LANG_ADD("wansetting", 			"WAN口设置", 	"Wan Setting"),
		EB_LANG_ADD("macclone", 			"MAC地址克隆", 	"Mac Clone"),
    	EB_LANG_ADD("dhcpserver", 			"DHCP服务",		"Dhcp Server"), 
    	EB_LANG_ADD("dhcpclients", 			"客户端列表", 	"Dhcp Clients"), 
		EB_LANG_ADD("dhcpfixmap", 			"静态地址分配", "Dhcp Fix Map"), 
    	EB_LANG_ADD("natvirtualserver", 	"虚拟服务器", 	"Virtual Server"), 
    	EB_LANG_ADD("natspecial_app", 		"特殊应用程序", "Special App"), 
		EB_LANG_ADD("natdmz", 				"DMZ主机", 		"DMZ Setting"), 
		EB_LANG_ADD("natupnp", 				"UPnP设置", 	"Upnp Setting"), 
    	EB_LANG_ADD("securityfirewall", 	"防火墙设置", 	"Firewall"), 
    	EB_LANG_ADD("securityipfilter", 	"IP地址过滤", 	"Ipfilter"), 
		EB_LANG_ADD("securitydomainfilter", "域名过滤", 	"Domain Filter"), 
		EB_LANG_ADD("securitymacfilter", 	"MAC地址过滤", 	"Mac Filter"), 
		EB_LANG_ADD("securityremoteweb", 	"远端WEB管理", 	"Remote Web"), 
		EB_LANG_ADD("securityping", 		"WAN口Ping", 	"Ping"), 
    	EB_LANG_ADD("routestatic", 			"静态路由表", 	"Static Route"),
    	EB_LANG_ADD("systemupgrade", 		"软件升级", 	"Upgrade"), 
    	EB_LANG_ADD("systemrestore", 		"恢复出厂设置", "Restore"), 
		EB_LANG_ADD("systemreboot", 		"重启路由器", 	"Reboot"), 
		EB_LANG_ADD("systemaccount", 		"修改登录口令", "Account"), 
		EB_LANG_ADD("systemlog", 			"系统日志",  	"System Log"),
    	EB_LANG_ADD("basicstatus", 			"运行状态", 	"Basic Status"),
    	EB_LANG_ADD("basicguide", 			"设置向导", 	"Basic Guide"),   
    	EB_LANG_ADD("network", 	"网络参数", 	"Network"),   
    	EB_LANG_ADD("dhcpserver", 			"DHCP服务器", 	"Dhcp Server"), 
    	EB_LANG_ADD("nat", 					"转发规则", 	"Nat Rule"),   
    	EB_LANG_ADD("security", 			"安全设置", 	"Security"),   
    	EB_LANG_ADD("route", 				"路由功能", 	"Route"),   
    	EB_LANG_ADD("systetool", 			"系统工具", 	"Systemupgrade"),   
	
		EB_LANG_ADD(NULL, NULL, NULL)
	};
